require("core.lazy")
require("core.lsp")
require("core.treesitter")
require("core.options")
require("core.mason")
require("core.cmp")
require("core.keymaps")
require("core.nvim-tree")
require("core.bufferline")
require("core.colorscheme")
require("core.codium")
require("core.toggleterm")
require("core.lualine")
require("core.hot-reload")
require("flutter-tools").setup {} -- use defaults
