#!/bin/sh
alias vim='nvim'
alias sx='~/scripts/xsh.sh'
alias warp-svc='sudo warp-svc'
alias xpdf='xpdf -z 250'
alias f='~/scripts/fzf.sh'
alias p='sudo pacman -S'
alias pa='paru -S'
alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias arafyne="export FYNE_FONT="/media/Maind/arial-cufonfonts/ARIAL.TTF""
alias lg="lazygit"
alias fb='flutter build apk --release --target-platform android-arm64'
alias fr= 'flutter run -d linux'
pandoc(){
  docker run --rm --volume $(pwd):/data pandoc/latex $@
}
ocrd(){
for f in ./*.pdf; do ocrmypdf "$f" "$(basename "$f" ".pdf")_ocr.pdf"; done 
}
# setxkbmap -option grp:alt_shift_toggle us,ar
# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
gowr(){
    gow -c -e=go,mod,tmpl run $1
}

alias dockerre='docker restart personal_db'
alias dockerex='docker exec -it personal_db psql -U postgres'
# /media/Maind/docker/volumes/personal_lib_db/_data:/var/lib/postgresql/data

# confirm before overwriting something
alias rm='rm -i'

alias df='df -h'     # human-readable sizes

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

case "$(uname -s)" in

    Darwin)
        # echo 'Mac OS X'
        alias ls='ls -G'
        ;;

    Linux)
        alias ls='ls --color=auto'
        ;;

    CYGWIN* | MINGW32* | MSYS* | MINGW*)
        # echo 'MS Windows'
        ;;
    *)
        # echo 'Other OS'
        ;;
esac
