adjust_column_width 0
disable_ligatures   cursor
font_size 13.0

# Colors
# ftpd gruvbox
foreground     #ebdbb2
background     #12121A 
cursor         #ebdbb2

# Cursor {{{
cursor_shape               block
cursor_blink_interval      -1
cursor_stop_blinking_after 15.0
# }}}

# Scrollback {{{
scrollback_lines              2000
scrollback_pager              less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
scrollback_pager_history_size 0
wheel_scroll_multiplier       5.0
touch_scroll_multiplier       1.0
# }}}


# Mouse {{{
mouse_hide_wait             3.0
url_color                   #458588
url_style                   single
open_url_modifiers          kitty_mod
open_url_with               qutebrowser
url_prefixes                http https file ftp gemini
detect_urls                 yes
copy_on_select              kitty_select
strip_trailing_spaces       smart
rectangle_select_modifiers  ctrl+alt
terminal_select_modifiers   shift
select_by_word_characters   @-./_~?&=%+#
click_interval              -1.0
focus_follows_mouse         no
pointer_shape_when_grabbed  arrow
default_pointer_shape       beam
pointer_shape_when_dragging beam
# }}}
# Performance {{{
repaint_delay   10
input_delay     3
sync_to_monitor yes
# }}}
# Bell {{{
enable_audio_bell    no
visual_bell_duration 0
window_alert_on_bell yes
bell_on_tab          yes
command_on_bell      none
# }}}


# Advanced settings {{{
shell                /usr/bin/zsh
editor               vim
close_on_child_death yes
allow_remote_control yes
listen_on            unix:/tmp/mykitty
clipboard_control    write-clipboard write-primary
allow_hyperlinks     yes
term                 xterm-kitty
# }}}


# BEGIN_KITTY_FONTS
font_family      family='Hack Nerd Font' postscript_name=HackNF-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
